curl -X POST https://agents.colosseum.com/api/my-project \
  -H "Authorization: Bearer e462b2694a5a4f298493dd1b5b7e31e0bd3779536969ce6243b6aad089c0f9eb" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "DAIN - Autonomous Trading OS",
    "description": "The operating system for autonomous trading agents. 7 integrated services, 80,000+ lines of production code. Your agent trades Solana DEXs, prediction markets, and perpetual futures without wallet popups or human babysitting. Signal -> Decide -> Execute -> Adapt.",
    "tags": ["ai", "defi", "trading"],
    "liveAppLink": "https://dain-2462103739.us-central1.run.app",
    "repoLink": "https://github.com/shreed27/DAIN",
    "solanaIntegration": "Deep Solana integration via Jupiter V6 for DEX routing and best price aggregation across all Solana DEXs. Implements limit orders with 30-second auto-execution polling. Full portfolio tracking for SOL and all SPL tokens using @solana/web3.js and @solana/spl-token. Agent keypair generation and management with secure key storage. Real-time transaction submission via Helius RPC with priority fee optimization. Trade history audit log stored on-chain in custom PDAs. Integrates with solana-agent-kit for seamless agent framework compatibility.",
    "problemStatement": "AI agents need to trade, but current options are broken. Option A: Give your agent a wallet and pray - no permissions, no limits, no kill switch. One bad trade and your treasury is gone. Option B: Build everything yourself - Jupiter integration, exchange APIs, risk management, order routing. Thats 6 months of work before your agent makes its first trade. There is no operating system for autonomous trading. Agents today are either dangerously unrestricted or painfully limited. Developers building trading bots on Eliza or solana-agent-kit are copy-pasting Jupiter code, writing their own retry logic, and hoping their agent doesnt blow up the treasury.",
    "technicalApproach": "Built as a 7-service microservices architecture orchestrated through a central API gateway. Frontend: Next.js 14 with TypeScript, Tailwind CSS, and Framer Motion for real-time trading dashboard (25+ pages, 80,000+ lines of code). Backend: Node.js orchestrator with permission checking, risk validation, and execution routing. Solana integration via Jupiter V6 API for swap routing, @solana/web3.js for transaction construction, and Helius RPC for reliable submission with priority fees. Polymarket integration uses EIP-712 order signing for real (not mocked) order execution. Survival Mode implements a state machine with auto risk management at 50%/85%/120% P&L thresholds. X402 protocol integration on Base for agent-to-agent payments. Copy trading system monitors whale wallets via Helius webhooks and replicates positions with configurable sizing rules. SDK provides framework integrations for Eliza, solana-agent-kit, Claude MCP, and LangChain. All services containerized with Docker, deployed on Google Cloud Run with auto-scaling.",
    "targetAudience": "Primary audience: AI agent developers building trading bots on Eliza or solana-agent-kit frameworks. These developers currently spend 3-6 months building trading infrastructure from scratch - integrating Jupiter, writing retry logic, implementing risk management, and building order routing. With DAIN, they get 3 lines of SDK code: agent registers, gets permissioned wallet access, trades through unified API with kill switch and Survival Mode built-in. Secondary audience: DeFi protocols needing agent-compatible infrastructure for copy trading systems, yield optimizers, prediction market aggregators, and cross-chain arbitrage bots. These teams need reliable, production-grade trading infrastructure that can handle autonomous decision-making without constant human oversight.",
    "businessModel": "Phase 1 (Current): Free and open-source to maximize adoption and establish DAIN as the standard runtime for autonomous trading agents. Phase 2: Hosted infrastructure service at $99/month for managed orchestration, kill switch API, risk dashboard, and monitoring - saving teams 3 months of infrastructure work. Target 100 paying customers = $10k MRR within 6 months. Phase 3 (6 months): Transaction fees of 0.1% on routed volume. At $10M daily volume across all agents = $10k/day revenue = $3.6M annual run rate. Long-term: DAIN token for governance, agent reputation staking, and protocol revenue sharing. Revenue from enterprise licensing for institutional trading desks and hedge funds deploying autonomous strategies.",
    "competitiveLandscape": "Generic agent frameworks (Eliza, AutoGPT) provide no trading primitives - developers must build everything themselves. Exchange SDKs (Jupiter, Drift) are single-exchange focused with no orchestration or risk management. Wallet-as-a-service providers (Privy, Dynamic) only handle authentication, not trading logic. Trading platforms (Jupiter UI, Birdeye) are built for humans, not agents - they require wallet popups and manual confirmation. DAIN is the only complete stack combining authentication + permissions + execution + risk management + multi-market routing in one system. Our advantage: purpose-built for autonomous agents, production-ready infrastructure (80,000+ lines of battle-tested code), real order execution (not mocked), and framework integrations that work out of the box. Closest competitor would be building your own infrastructure, which takes 6 months and costs $200k+ in developer time.",
    "futureVision": "1 month: MCP server for Claude integration, AutoGPT/LangGraph integrations. 3 months: Cross-chain trading via Wormhole (Ethereum, Arbitrum, Base), Drift perpetuals, Zeta options, Marginfi lending. 6 months: On-chain reputation system, strategy marketplace, institutional features (multi-sig, compliance, OTC). 12 months: Industry standard for autonomous trading. Raise Series A ($5M) from Solana VCs. Full-time team with 7 years DeFi experience, connections to Solana Foundation, Jupiter, Helius. Target: 10,000 active agents, $100M daily volume."
  }'
